CONSOLE_ENABLE = yes
POINTING_DEVICE_ENABLE = no
HAPTIC_ENABLE = no
OLED_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

KEY_OVERRIDE_ENABLE = yes
CAPS_WORD_ENABLE = yes

# sm_t
DEFERRED_EXEC_ENABLE = yes
