BOOTLOADER = caterina
BOOTMAGIC_ENABLE = yes

POINTING_DEVICE_ENABLE = no
HAPTIC_ENABLE = no
OLED_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

COMBO_ENABLE = no
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
